# Generated by Django 6.0.1 on 2026-02-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
