# Generated by Django 6.0.1 on 2026-02-27 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0002_alter_tenant_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='Rentals.room'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='Rentals.tenant'),
        ),
    ]
